/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "inverse-surface": "#2b3137",
        "on-secondary": "#ffffff",
        "surface-bright": "#f7f9ff",
        "secondary-container": "#e1dfdb",
        "on-surface-variant": "#434844",
        "primary-fixed-dim": "#b7ccbc",
        "secondary-fixed-dim": "#c8c6c2",
        "surface-dim": "#d5dae2",
        "on-secondary-container": "#63635f",
        "surface-container-low": "#eff4fc",
        "surface-container-lowest": "#ffffff",
        "error-container": "#ffdad6",
        "surface-tint": "#506356",
        secondary: "#5e5e5b",
        "surface-variant": "#dde3eb",
        "on-primary": "#ffffff",
        "on-error-container": "#93000a",
        "inverse-primary": "#b7ccbc",
        "on-surface": "#161c22",
        "on-secondary-fixed": "#1b1c19",
        "on-error": "#ffffff",
        "surface-container": "#e9eef6",
        "tertiary-fixed-dim": "#ccc5be",
        "on-secondary-fixed-variant": "#474744",
        "primary-container": "#66796c",
        "on-background": "#161c22",
        "on-tertiary-fixed": "#1e1b16",
        "on-tertiary": "#ffffff",
        primary: "#4d6054",
        outline: "#737873",
        "surface-container-highest": "#dde3eb",
        error: "#ba1a1a",
        "on-primary-fixed-variant": "#384b3f",
        "on-tertiary-fixed-variant": "#4a4640",
        "on-tertiary-container": "#fffbff",
        "secondary-fixed": "#e4e2dd",
        background: "#f7f9ff",
        "tertiary-container": "#79746d",
        surface: "#f7f9ff",
        "tertiary-fixed": "#e9e1d9",
        "on-primary-container": "#f6fff6",
        tertiary: "#605b55",
        "inverse-on-surface": "#ecf1f9",
        "primary-fixed": "#d2e8d8",
        "outline-variant": "#c3c8c2",
        "surface-container-high": "#e3e9f0",
        "on-primary-fixed": "#0d1f15",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        xs: "4px",
        "container-max": "1200px",
        base: "8px",
        "margin-mobile": "20px",
        lg: "48px",
        sm: "12px",
        xl: "80px",
        gutter: "24px",
        md: "24px",
      },
      fontFamily: {
        // Mapping standard keys to the fonts used in your HTML spec
        serif: ["Playfair Display", "serif"],
        sans: ["Plus Jakarta Sans", "sans-serif"],
        "display-lg": ["Playfair Display", "serif"],
        "headline-md": ["Playfair Display", "serif"],
      },
      fontSize: {
        "display-lg-mobile": ["36px", { lineHeight: "44px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-lg": ["20px", { lineHeight: "32px", fontWeight: "400" }],
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "label-sm": ["12px", { lineHeight: "16px", letterSpacing: "0.03em", fontWeight: "500" }],
        "headline-md": ["32px", { lineHeight: "40px", fontWeight: "600" }],
        "label-md": ["14px", { lineHeight: "20px", letterSpacing: "0.05em", fontWeight: "600" }],
        "headline-md-mobile": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "body-md": ["18px", { lineHeight: "28px", fontWeight: "400" }],
      },
      keyframes: {
        breathe: {
          "0%, 100%": { transform: "scale(1)", opacity: "0.3" },
          "50%": { transform: "scale(1.05)", opacity: "0.15" },
        },
        fadeInUp: {
          "0%": { opacity: "0", transform: "translateY(20px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
      },
      animation: {
        breathe: "breathe 10s ease-in-out infinite",
        "fade-in-up": "fadeInUp 0.8s cubic-bezier(0.16, 1, 0.3, 1) forwards",
      },
    },
  },
  plugins: [
    require("@tailwindcss/forms"),
    // Adding a small plugin to handle the Material Symbol "FILL" state more easily
    function ({ addUtilities }) {
      addUtilities({
        '.fill-0': { 'font-variation-settings': '"FILL" 0' },
        '.fill-1': { 'font-variation-settings': '"FILL" 1' },
      })
    }
  ],
}