/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        // Dynamic theme colors (controlled by CSS variables)
        primary: {
          50: 'var(--color-primary-50)',
          100: 'var(--color-primary-100)',
          200: 'var(--color-primary-200)',
          300: 'var(--color-primary-300)',
          400: 'var(--color-primary-400)',
          500: 'var(--color-primary-500)',
          600: 'var(--color-primary-600)',
          700: 'var(--color-primary-700)',
          800: 'var(--color-primary-800)',
          900: 'var(--color-primary-900)',
          DEFAULT: 'var(--color-primary)',
        },
        accent: {
          50: 'var(--color-accent-50)',
          100: 'var(--color-accent-100)',
          200: 'var(--color-accent-200)',
          300: 'var(--color-accent-300)',
          400: 'var(--color-accent-400)',
          500: 'var(--color-accent-500)',
          600: 'var(--color-accent-600)',
          700: 'var(--color-accent-700)',
          800: 'var(--color-accent-800)',
          900: 'var(--color-accent-900)',
          DEFAULT: 'var(--color-accent)',
        },
        background: {
          light: 'var(--bg-light)',
          dark: 'var(--bg-dark)',
          card: 'var(--bg-card)',
          elevated: 'var(--bg-elevated)',
          surface: 'var(--bg-surface)',
          DEFAULT: 'var(--bg-light)',
        },
        text: {
          primary: 'var(--text-primary)',
          secondary: 'var(--text-secondary)',
          tertiary: 'var(--text-tertiary)',
          inverse: 'var(--text-inverse)',
        },
        border: {
          light: 'var(--border-light)',
          dark: 'var(--border-dark)',
          DEFAULT: 'var(--border-default)',
        },
        
        // Legacy color system (keep for backward compatibility)
        "inverse-surface": "#2b3137",
        "on-secondary": "#ffffff",
        "surface-bright": "#f7f9ff",
        "secondary-container": "#e1dfdb",
        "on-surface-variant": "#434844",
        "primary-fixed-dim": "#b7ccbc",
        "secondary-fixed-dim": "#c8c6c2",
        "surface-dim": "#d5dae2",
        "on-secondary-container": "#63635f",
        "surface-container-low": "#eff4fc",
        "surface-container-lowest": "#ffffff",
        "error-container": "#ffdad6",
        "surface-tint": "#506356",
        secondary: "#5e5e5b",
        "surface-variant": "#dde3eb",
        "on-primary": "#ffffff",
        "on-error-container": "#93000a",
        "inverse-primary": "#b7ccbc",
        "on-surface": "#161c22",
        "on-secondary-fixed": "#1b1c19",
        "on-error": "#ffffff",
        "surface-container": "#e9eef6",
        "tertiary-fixed-dim": "#ccc5be",
        "on-secondary-fixed-variant": "#474744",
        "primary-container": "#66796c",
        "on-background": "#161c22",
        "on-tertiary-fixed": "#1e1b16",
        "on-tertiary": "#ffffff",
        "legacy-primary": "#4d6054",
        outline: "#737873",
        "surface-container-highest": "#dde3eb",
        error: "#ba1a1a",
        "on-primary-fixed-variant": "#384b3f",
        "on-tertiary-fixed-variant": "#4a4640",
        "on-tertiary-container": "#fffbff",
        "secondary-fixed": "#e4e2dd",
        "legacy-background": "#f7f9ff",
        "tertiary-container": "#79746d",
        surface: "#f7f9ff",
        "tertiary-fixed": "#e9e1d9",
        "on-primary-container": "#f6fff6",
        tertiary: "#605b55",
        "inverse-on-surface": "#ecf1f9",
        "primary-fixed": "#d2e8d8",
        "outline-variant": "#c3c8c2",
        "surface-container-high": "#e3e9f0",
        "on-primary-fixed": "#0d1f15",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
        full: "9999px",
      },
      spacing: {
        xs: "4px",
        "container-max": "1200px",
        base: "8px",
        "margin-mobile": "20px",
        lg: "48px",
        sm: "12px",
        xl: "80px",
        gutter: "24px",
        md: "24px",
      },
      fontFamily: {
        serif: ["Playfair Display", "Georgia", "serif"],
        sans: ["Inter", "Plus Jakarta Sans", "system-ui", "sans-serif"],
        "display-lg": ["Playfair Display", "Georgia", "serif"],
        "headline-md": ["Playfair Display", "Georgia", "serif"],
        mono: ["JetBrains Mono", "monospace"],
      },
      fontSize: {
        "display-lg-mobile": ["36px", { lineHeight: "44px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-lg": ["20px", { lineHeight: "32px", fontWeight: "400" }],
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "label-sm": ["12px", { lineHeight: "16px", letterSpacing: "0.03em", fontWeight: "500" }],
        "headline-md": ["32px", { lineHeight: "40px", fontWeight: "600" }],
        "label-md": ["14px", { lineHeight: "20px", letterSpacing: "0.05em", fontWeight: "600" }],
        "headline-md-mobile": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "body-md": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        xs: ["12px", { lineHeight: "16px" }],
        sm: ["14px", { lineHeight: "20px" }],
        base: ["16px", { lineHeight: "24px" }],
        lg: ["18px", { lineHeight: "28px" }],
        xl: ["20px", { lineHeight: "28px" }],
        "2xl": ["24px", { lineHeight: "32px" }],
        "3xl": ["30px", { lineHeight: "36px" }],
        "4xl": ["36px", { lineHeight: "40px" }],
      },
      keyframes: {
        breathe: {
          "0%, 100%": { transform: "scale(1)", opacity: "0.3" },
          "50%": { transform: "scale(1.05)", opacity: "0.15" },
        },
        fadeInUp: {
          "0%": { opacity: "0", transform: "translateY(20px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
        fadeIn: {
          "0%": { opacity: "0" },
          "100%": { opacity: "1" },
        },
        slideIn: {
          "0%": { transform: "translateX(-100%)" },
          "100%": { transform: "translateX(0)" },
        },
        pulse: {
          "0%, 100%": { opacity: "1" },
          "50%": { opacity: "0.5" },
        },
      },
      animation: {
        breathe: "breathe 10s ease-in-out infinite",
        "fade-in-up": "fadeInUp 0.8s cubic-bezier(0.16, 1, 0.3, 1) forwards",
        "fade-in": "fadeIn 0.5s ease-out forwards",
        "slide-in": "slideIn 0.3s ease-out forwards",
        "pulse-slow": "pulse 3s ease-in-out infinite",
      },
      backdropBlur: {
        xs: "2px",
        sm: "4px",
        md: "8px",
        lg: "12px",
        xl: "24px",
        "2xl": "40px",
      },
      boxShadow: {
        "glass": "0 8px 32px rgba(0, 0, 0, 0.04)",
        "glass-lg": "0 20px 50px rgba(0, 0, 0, 0.06)",
        "glass-xl": "0 30px 70px rgba(0, 0, 0, 0.08)",
      },
    },
  },
  plugins: [
    require("@tailwindcss/forms"),
    require("@tailwindcss/typography"),
    // Plugin for Material Symbol FILL state
    function ({ addUtilities }) {
      addUtilities({
        '.fill-0': { 'font-variation-settings': '"FILL" 0' },
        '.fill-1': { 'font-variation-settings': '"FILL" 1' },
        '.wght-300': { 'font-variation-settings': '"wght" 300' },
        '.wght-400': { 'font-variation-settings': '"wght" 400' },
        '.wght-500': { 'font-variation-settings': '"wght" 500' },
        '.wght-600': { 'font-variation-settings': '"wght" 600' },
        '.wght-700': { 'font-variation-settings': '"wght" 700' },
      })
    }
  ],
}