import { NextResponse } from 'next/server';
import { prisma } from '@/lib/prisma';
import { getServerSession } from 'next-auth';
import { authOptions } from "@/lib/auth";

export async function GET() {
  try {
    const session = await getServerSession(authOptions);
    if (!session?.user?.id) {
      return NextResponse.json({ error: 'Unauthorized cohort context' }, { status: 401 });
    }

    // Identify which cohort group this active user belongs to
    const memberRecord = await prisma.cohortMember.findUnique({
      where: { userId: session.user.id },
      include: { cohort: true },
    });

    if (!memberRecord) {
      // If no cohort assignment exists yet, fall back gracefully to a baseline global group
      return NextResponse.json({
        progress: {
          groupName: 'Sanctuary Open Cohort',
          totalMembers: 1,
          completedCount: 1,
          activeBook: 'John',
          activeChapter: 15,
        },
        messages: [],
      });
    }

    const cohortId = memberRecord.cohortId;

    // Get count metrics for calculation engines
    const totalGroupCount = await prisma.cohortMember.count({ where: { cohortId } });
    
    // Check total community share entries generated by this group's members specifically for today's assignment
    const startOfToday = new Date();
    startOfToday.setHours(0, 0, 0, 0);

    const distinctCompletionsToday = await prisma.communityShare.findMany({
      where: {
        book: 'John', // This should link dynamically to a reading plan table in production
        chapter: 15,
        createdAt: { gte: startOfToday },
        userId: {
          in: (await prisma.cohortMember.findMany({
            where: { cohortId },
            select: { userId: true },
          })).map((m) => m.userId),
        },
      },
      distinct: ['userId'],
    });

    // Pull last 25 stream messages sequentially
    const messages = await prisma.cohortMessage.findMany({
      where: { cohortId },
      orderBy: { createdAt: 'asc' },
      take: 25,
      include: { user: { select: { name: true } } },
    });

    return NextResponse.json({
      progress: {
        groupName: memberRecord.cohort.name,
        totalMembers: totalGroupCount || 1,
        completedCount: distinctCompletionsToday.length,
        activeBook: 'John',
        activeChapter: 15,
      },
      messages: messages.map((m) => ({
        id: m.id,
        user: {
          name: m.user.name || 'Circle Member',
          initials: (m.user.name || 'CM').split(' ').map((n) => n[0]).join('').toUpperCase().substring(0, 2),
        },
        text: m.text,
        timestamp: m.createdAt.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }),
      })),
    });
  } catch (error) {
    console.error('CRITICAL_COHORT_SYNC_ERR:', error);
    return NextResponse.json({ error: 'Cohort parsing sub-routing failure' }, { status: 500 });
  }
}